name: Deploy and Promote (master)
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: CI=false yarn build
      - uses: google-github-actions/deploy-appengine@main
        with:
          promote: true
          credentials: ${{ secrets.gcp_credentials }}