name: Deploy (develop)
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: google-github-actions/deploy-appengine@main
        with:
          promote: false
          credentials: ${{ secrets.gcp_credentials }}